/**
 * Noms de routes centralises (utilises avec `router.push({ name: ... })`)
 * pour eviter les chaines litterales eparpillees dans le code.
 */
export const ROUTE_NAMES = {
  login: 'login',
  register: 'register',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  dashboard: 'dashboard',
  clients: 'clients',
  clientDetail: 'client-detail',
  products: 'products',
  productDetail: 'product-detail',
  invoices: 'invoices',
  invoiceCreate: 'invoice-create',
  invoiceDetail: 'invoice-detail',
  quotes: 'quotes',
  quoteCreate: 'quote-create',
  quoteDetail: 'quote-detail',
  creditNotes: 'credit-notes',
  payments: 'payments',
  reports: 'reports',
  users: 'users',
  subscription: 'subscription',
  settings: 'settings',
  support: 'support',
  supportDetail: 'support-detail',
  notFound: 'not-found',
  forbidden: 'forbidden',
  impersonate: 'impersonate',
  adminLogin: 'admin-login',
  adminDashboard: 'admin-dashboard',
  adminBusinesses: 'admin-businesses',
  adminBusinessDetail: 'admin-business-detail',
  adminPlans: 'admin-plans',
  adminAdmins: 'admin-admins',
  adminSupport: 'admin-support',
  adminSupportDetail: 'admin-support-detail',
  adminSettings: 'admin-settings'
} as const
